### ISSUE TITLE
Build Error while building aperturejs

### ISSUE THREAD

**Issue by mkesavan13** [unchartedsoftware/aperturejs#22]
I am trying to build aperturejs with Readme.md instructions.

I cloned the repository and tried the command **mvn clean install** in the root directory of ApertureJs.

I got the following Build Error as in the screenshot,
![aperture graph error](https://cloud.githubusercontent.com/assets/8044050/14953974/34e886d2-108c-11e6-9b08-e289a9e61eaa.PNG)

I am using the latest version of Maven - 3.3.9

Thanks in advance.

**Comment by cdbethune** [comment]
It looks like the repo that was supplying `javaml.jar` used in the `aperture-graph` sub-project is no longer publicly available.  As a work around, in `aperture-graph/pom.xml` you can replace

````xml
<repository>
    <id>codelutin</id>
    <name>Code Lutin</name>
    <url>http://devel.summitsystemsinc.net/artifactory/repo/</url>
</repository>
```
with

````xml
<repository>
    <id>streamreasoning</id>
    <name>Stream Reasoning</name>
    <url>http://streamreasoning.org/maven</url>
</repository>
```

**Comment by mkesavan13** [comment]
Wow Chris. That worked. You're awesome

Thank you.

**Comment by mkesavan13** [comment]
Chris,
I have a couple of questions to ask. By bullet points,
- I saw one another issue in which you have advised the other user to go with Aperture Salt. We're yet to start with our work with ApertureJS. My question is Should salt be preferred over ApertureJs? Refer: https://github.com/unchartedsoftware/aperture-tiles/issues/317
- Secondly, How different is Salt from ApertureJs and what is the technology behind Salt? 

Thanks in advance.

**Comment by cdbethune** [comment]
ApertureTiles is a suite of tools that we built as part of our research into tile-based visual analytics at scale. It consists of 1) a Spark-based tile generation library, 2) a server (java / Tomcat), and 3) a simple web client framework for visualizing tiles.  ApertureJS is a visualization framework that we used in building the client and server portions of ApertureTiles.

[Salt] (https://github.com/unchartedsoftware/salt) is a new library that provides the same baseline functionality as the Spark-based tile generation component in ApertureTiles, but also introduces new capabilities, and provides a cleaner and more flexible API.  It does not provide a server component or client framework, but there are a number of examples available in the [Salt Examples] (https://github.com/unchartedsoftware/salt) project that show you can get something up pretty quickly using a standard map framework like Leaflet.  It's also worth mentioning that we're closing in on releasing Salt.js, which is a client-side library that will provide functions for some common rendering cases we've encountered.  Our development and support efforts will be primarily focused on Salt moving forward, so I would suggest using it rather than ApertureTiles if you're starting a new project.
